### PR TITLE
Update municipalities after spellcheck and deduplication

### PR DESCRIPTION
**Pull request by estherwn**

### CODE REVIEW

**Review by SamLubbers — APPROVED** [review]
@estherwn super! fijn dat je deze laatste correcties hebt gedaan :raised_hands:

**Comment by SamLubbers** [comment]
@estherwn sorry I first merged your commit and only after I checked for inconsistencies. Here are the last few things that need to be fixed:

gemeentes die er 2 keer in staan:

- Leidendorp
- Midden Delfland
- Midden Groningen
- Súdwest Fryslân

gemeentes die er 2 keer in staan (met typos):

- Bergen (NH) (je hebt ook: Bergen (NH.))
- Doesborg (je hebt ook: Doesburg)
- Doetingchem (je hebt ook: Doetinchem)
- Meersen (je hebt ook: Meerssen)
- Niederweert (je hebt ook: Nederweert)
- Noord Beveland (je hebt ook: Noord-Beveland)
- Oost-Zaan (je hebt ook: Oostzaan)
- Sint Anthonius (je hebt ook: Sint Anthonis)

gemeente combinaties:

- Arnhem/Nijmegen (je hebt ook Arnhem en Nijmegen apart)
- Leeuwarden/Fryslân (je hebt ook Leeuwarden en Fryslan apart)

---

de volgende gemeentes waren niet in de custom field in Action Network. Het is goed dat deze er nu wel in staan toch?:

- Akersloot
- Cuijk
- 's-Gravenhage
- Zaanstreek

**Comment by estherwn** [comment]
#@SamLubbers ,

The names you mention are intentionally taken out of the AN field and are left in the config on purpose. Reason for this is that old registrations still have this municipality and in my opinion they should be mapped to a group. As long as there are no exact duplicates, there is no issue for the script and result.

Further explanation below

The following are replaced with correct spelling:
```
Incorrect spelling - Correct spelling
-------------------------------------
Leidendorp         - Leiderdorp
Midden Delfland    - Midden-Delfland
Midden Groningen   - Midden-Groningen
Súdwest Fryslân    - Súdwest-Fryslân
Bergen (NH.)       - Bergen (NH)
Doesborg           - Doesburg
Doetingchem        - Doetinchem
Meersen            - Meerssen
Niederweert        - Nederweert
Noord Beveland     - Noord-Beveland
Oost-Zaan          - Oostzaan
Sint Anthonius     - Sint Anthonis
```

- [ ] Reflecting on this, I think that "Bergen (L.)" and "Bergen (NH.)" should probably be without a dot. I'll add those to the config and change the AR-list. 

The following are taken out of the AR-list:
```
Akersloot       > Is a village in municipality "Castricum"
Cuijk           > Became part of "Land van Cuijk", which is the new name for this municipality
's-Gravenhage   > Replaced by "Den Haag"
Zaanstreek      > Is not a municipality
```

Other items that are removed from the AR-list are:
```
Beemster                > Fused with "Purmerend"
Krimpen aan de IJssel   > Is part of "Krimpenerwaard"
Langedijk               > Fused with "Heerhugowaard"
U[bewerken              > Typo in the old AR-list
```

- [ ] And in going through the list I realised I forgot to remove "Weesp", which fused with "Amsterdam". So I'll remove Weesp from the AR-list.

**Comment by SamLubbers** [comment]
@estherwn wow. Thank you for the super and beautifully formatted explanation :star2: Now I understand why there are a bunch of municipalities not included in the AN list, but included in the config.

**Pull request merged**
